services:
  database_devops_app:
    image: postgres
    container_name: database_devops_app
    restart: always
    ports:
      - 1234:5432
    env_file:
      - ./back-end/.env.test
    volumes:
      - database:/var/lib/postgresql/data

  node_devops_app:
    container_name: node_devops_app
    build: ./back-end
    ports:
      - 5000:5000
    depends_on:
      - database_devops_app
    env_file:
      - back-end/.env.test

volumes:
  database:
