name: Tests_on_Pull_Request

on: [pull_request]

jobs: 
  Tests_on_Pull_Request: 
    runs-on: ubuntu-latest
    steps:
      - name: Check out respository code
        uses: actions/checkout@v3
      - name: Create env file
        uses: SpicyPizza/create-envfile@v1
        with: 
          envkey_DATABASE_URL: ${{secrets.DATABASE_URL}}
          envkey_POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          envkey_POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          envkey_POSTGRES_DB: ${{secrets.POSTGRES_DB}}
        file_name: .env.test
      - name: Run tests
        run: docker-compose -f docker-compose-test.yml run node_devops_app npm run test

